version: "3.9"

services:
  frontend:
    build:
      context: .
    expose:
      - "5173"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.routers.fe.rule=Host(`open-overlays.luxterful.eu`)"
      - "traefik.http.services.fe.loadbalancer.server.port=5173"
      - "traefik.http.routers.fe.tls=true"
      - "traefik.http.routers.fe.tls.certresolver=acmeresolver"
    networks:
      - shared
    command: ["npm", "run", "serve"]